/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tf2.spyhitbox;

import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author JayPC
 */
public class testYourSelf extends javax.swing.JFrame {

    /**
     * Creates new form testYourSelf
     */
    
    ImageIcon scout1 = new ImageIcon(new ImageIcon((getClass().getResource("/scout1.png"))).getImage().getScaledInstance(300, 500, Image.SCALE_DEFAULT));
    ImageIcon scout2 = new ImageIcon(new ImageIcon((getClass().getResource("/demo_back.jpg"))).getImage().getScaledInstance(300, 500, Image.SCALE_DEFAULT));
    
    JButton button1 = new JButton("Button1");
    JPanel panel1 = new JPanel();
    JPanel panel2 = new JPanel();
    JPanel panel3 = new JPanel();
    
    // this label changes to the image 
    JLabel classLabel = new JLabel ();
    JLabel answerLabel = new JLabel();
    
    public testYourSelf() {
        
        initComponents();
        scoutHead.setEnabled(false);
        demoHead.setEnabled(false);
        System.out.println(this.getLayout());

        //scoutHead.setOpaque(false);
        //scoutHead.setContentAreaFilled(false);
        //scoutHead.setBorderPainted(false);
        //scoutHead.setText("");
        panel1.setBounds(10, 50, 300, 500);
        panel1.setLayout(null);
        panel1.setBackground(Color.BLUE);
        // if you want to add border to the panel
        panel1.setBorder(BorderFactory.createBevelBorder(1));
        // this will limit the items inside the panel to only the dimensions of the pane (good for the class images?)
        panel1.setLayout(new BorderLayout());
        panel1.add(button1);
        
        panel2.setBounds(301, 50, 300, 500);
        panel2.setBackground(Color.YELLOW);
        
        
        
        panel3.setBounds(600, 50, 300, 500);
        panel3.setBackground(Color.GREEN);
        
        panel3.add(answerLabel);
        
        // Changing the background of the whole frame
        this.getContentPane().setBackground(new Color(150, 150, 150));
        // setting the window size of the frame
        this.setSize(1000, 800);
        
        picLabel.setText("");
        answerLabel.setText("");
        System.out.println(getClass().getResource("/scout1.png"));
  
        panel1.add(classLabel);
        classLabel.setText("");
        this.add(panel1);
        this.add(panel2);
        this.add(panel3);
        
        //this.setLayout(null);
        //panel.setVisible(true);
        
    }
    
    public void doStuff() {
        demoHead.setEnabled(true);
        scoutHead.setEnabled(false);
        classLabel.setIcon(scout2);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTitle = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        picLabel = new javax.swing.JLabel();
        scoutHead = new javax.swing.JButton();
        demo = new javax.swing.JButton();
        demoHead = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainTitle.setText("Welcome to cheetaz's Spy Hitbox Test :)");

        jButton1.setText("Scout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        picLabel.setText("pictureLabel");

        scoutHead.setText("scoutHead");
        scoutHead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoutHeadActionPerformed(evt);
            }
        });

        demo.setText("Demo");
        demo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoActionPerformed(evt);
            }
        });

        demoHead.setText("demoHead");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(mainTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(demoHead)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scoutHead, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(picLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(276, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(demo)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainTitle)
                        .addGap(48, 48, 48)
                        .addComponent(picLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(scoutHead, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(demoHead, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(demo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // This is for the "SCOUT" button
        scoutHead.setEnabled(true);
        demoHead.setEnabled(false);
        classLabel.setIcon(scout1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void scoutHeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoutHeadActionPerformed
        // TODO add your handling code here:
        answerLabel.setText("CORRECT! :D");
    }//GEN-LAST:event_scoutHeadActionPerformed

    private void demoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoActionPerformed
        // TODO add your handling code here:
        doStuff();
//        demoHead.setEnabled(true);
//        scoutHead.setEnabled(false);
//        classLabel.setIcon(scout2);
    }//GEN-LAST:event_demoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton demo;
    private javax.swing.JButton demoHead;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JLabel picLabel;
    private javax.swing.JButton scoutHead;
    // End of variables declaration//GEN-END:variables
}
